name: 'sp500_financials'
version: '1.0.0'
config-version: 2

profile: 'sp500_financials'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  sp500_financials:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
